### ISSUE TITLE
Version in release package is 1.0 instead of 1.0.1

### ISSUE THREAD

**Issue by Jeshibu** [NMaxCarr/GamingTimeManager#3]
https://github.com/NMaxCarr/GamingTimeManager/blob/e5eb90fbd7fcfd6ca9686e41e54c9201be6ccd89/extension.yaml

This results in Playnite repeatedly trying to update from 1.0 to 1.0.1, even when 1.0.1 is already installed, because it's falsely reporting as being 1.0.
You should re-release 1.0.1 with the current master branch's contents.

**Comment by NMaxCarr** [comment]
Thank you so much for your bug report. Really appreciated. I should have double-check this before release.  Should be fix now.
